name: Hello World with Manual Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name for manual input"
        required: false
        default: 'Tushar'

jobs:
  manual_input_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello, ${{ inputs.name }}"
