name: Hello World with Manual Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name for manual input"
        type: string
        required: false
        default: 'Tushar'
      age:
        description: "Age of the user"
        type: number
        required: true
        default: '0'

jobs:
  manual_input_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello, ${{ inputs.name }}"
        # run: echo "Hello, ${{ github.events.inputs.name }}"
      - name: Age
        run: echo "My age is ${{ github.event.inputs.age }}"
