name: Hello World with Manual Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name for manual input"
        type: string
        required: false
        default: 'Tushar'
      age:
        description: "Age of the user"
        type: number
        required: true
        default: '0'
      gender:
        description: "Gender of the user"
        type: choice
        options:
          - Male
          - Female
          - Trans
      marrital_status:
        description: "Marrital status of the user"
        type: boolien
      

jobs:
  manual_input_demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello, ${{ inputs.name }}"
        # run: echo "Hello, ${{ github.events.inputs.name }}"
      - name: Age
        run: echo "My age is ${{ github.event.inputs.age }}"
      - name: Gender
        run: echo "I am a ${{ github.event.inputs.gender }}"
      - name: Marrital Status
        run: echo "Married : ${{ github.event.inputs.marrital_status }}"
